### PR TITLE
Create plugin.yml

### PR DESCRIPTION
**Pull request by MCPEPIG**

### CODE REVIEW

**Comment by xxFlare** [comment]
Thanks. hopefully I will start coding this plugin soon.

**Comment by MCPEPIG** [comment]
No problem

**Comment by xxFlare** [comment]
So, Im guessing you like MushroomStewHeal? Because you seem interested in it :D

**Comment by MCPEPIG** [comment]
Yep

**Comment by xxFlare** [comment]
:+1:

**Comment by MCPEPIG** [comment]
I like all your plugins!

**Comment by xxFlare** [comment]
:D The best plugin I ever made is FlarehubCore.

**Comment by MCPEPIG** [comment]
And thats

**Comment by xxFlare** [comment]
and HG plugin, controls auth, pvp, matches, rotaing maps, refilling chests, reseting maps, commands, all in one plugin.

**Comment by xxFlare** [comment]
Its on my HG server.

**Comment by MCPEPIG** [comment]
Wow

**Comment by MCPEPIG** [comment]
Wat is added in your modified SimpleAuth thats here

**Comment by xxFlare** [comment]
I was going to modify it but instead I created a new plugin called xAuth.

**Comment by xxFlare** [comment]
Its not public but I can give you a copy.

**Comment by MCPEPIG** [comment]
Can I have a copy

**Comment by xxFlare** [comment]
One sec, Let me see if I can find a copy.

**Comment by MCPEPIG** [comment]
BTW, if you have kik, we could talk on kik instead of here :tongue:

**Comment by xxFlare** [comment]
Can't find a copy. But I have some code from it, so ill re-make it on github,

**Comment by MCPEPIG** [comment]
K

**Pull request merged**
